#!/bin/bash -l

#SBATCH -A uppmax2025-3-3
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 16
#SBATCH -t 08:00:00
#SBATCH -J gtdbtk_job
#SBATCH --mail-type=ALL
#SBATCH --mail-user=ashdos28@rackham.uppmax.uu.se
#SBATCH --output=%x.%j.out

# Load modules
module load bioinfo-tools
module load GTDB-Tk/2.4.0

# Define input and output directories
BINS_DIR="/home/ashdos28/scripts/quality_bins"
GTDB_OUT="/home/ashdos28/scripts/gtdbtk_out"

# Create output directory if it doesn't exist
mkdir -p "$GTDB_OUT"

# Run GTDB-Tk classify workflow
gtdbtk classify_wf \
  --genome_dir "$BINS_DIR" \
  --out_dir "$GTDB_OUT" --extension fa \
  --cpus 16 --skip_ani_screen

echo "GTDB-Tk classification complete!"
